### ISSUE TITLE
Input STL mesh import KO

### ISSUE THREAD

**Issue by yvanblanchard** [dennis2society/qtetramesher#1]
Hello,

I tried to import a STL mesh (size = 24 Mo, see link below), but it freezed.
I used the provided precompiled version "QTetraMesher_0.8.2.1_win_64_VS2015_VC14" (on Win10).

Thank you very much.

[thing_big.zip](https://github.com/dennis2society/qtetramesher/files/10932824/thing_big.zip)

**Comment by dennis2society** [comment]
Hi,
looks like I am using a very old version of trimesh2 which, when I included it into the project (2013 or so...), only had rudimentary support for STL import. Also I have never tested my project with such a big surface mesh....

The good news is that I have successfully loaded your model with QTetramesher after converting it to OBJ. Loading took quite a while (because the OBJ was ~95 MB), but I could even fill it with tetrahedra. Maybe you can for now try the convert-to-OBJ workaround. 

Replacing the surface mesh loading is on my todo list for quite a while already.

**Comment by yvanblanchard** [comment]
Yes, I tried the tetra meshing with this surface mesh, and it works fine, thank you (OBJ file loading was veeeeeerry slow, as you mentioned).
![image](https://user-images.githubusercontent.com/63931618/224116914-4905f680-aa6c-482e-abd3-6f1f673b50e1.png)
